### ISSUE TITLE
Integration draining Galaxy Watch battery?

### ISSUE THREAD

**Issue by davidalben** [Vedeneb/HA-SmartThings-Find#11]
First, thank you for share this integration. I've been searching for something like this.

But, since I've installed it in my Home Assistant, my Galaxy Watch 4 BT battery is being drained in a very fast way. Is it possible that the integration is doing this?

Is there a way to exclude a device from integration?

**Comment by Vedeneb** [comment]
Hi,
you might be right with that. It's quite possible that requesting a location update (which this integration does every 2 minutes) not only fetches the last information from the server but instead your phone actively tries to connect to the other device (in your case the watch) which would explain the battery drain.

> Is there a way to exclude a device from integration?

Yes, you can disable a device from the integrations page in Home Assistant. No location update requests will be made to disabled devices.

If you can confirm that the battery drain stops with the device disabled, I'll add a note to the readme and/or add an option to increase the polling interval.

**Comment by davidalben** [comment]
> you can disable a device from the integrations page in Home Assistant

Done. I'll keep you informed.

Thank you again, @Vedeneb!

**Comment by tomskra** [comment]
Hi, I have got similar problem with my Galaxy S23. My phone sometimes wakes up the screen for 1-2 seconds. I installed the NiceCatch app from Samsung and found out it’s happening because of “Find my mobile” Android app. I tried to disable integration in HA and the problem disappeared. You can see it in screenshots.

![Screenshot_20240613_103637_Nice Catch](https://github.com/Vedeneb/HA-SmartThings-Find/assets/11139471/32d47483-f723-4daa-b3a3-4d6720dff50f)


![1c04677db06c234d89739a24e14da59d9e1ee9fd](https://github.com/Vedeneb/HA-SmartThings-Find/assets/11139471/cded4d8e-a8d1-43cf-91a0-febec14ebb1e)


A temporary solution for me was to disable all entities in HA for my mobile phone. It looked like the problem with the screen wake-up disappeared. But today, the phone again starts to wake up. It's crazy how it drains the battery. 

![Screenshot_20240614_092940_Settings](https://github.com/Vedeneb/HA-SmartThings-Find/assets/11139471/26a72fed-ce12-4d1b-a824-d95e92beb809)


UPDATE: I maybe disabled only the device's entities before. Now, I disable the whole device. So, I will see if it helps.

**Comment by davidalben** [comment]
Well, I disabled the watch in the integration and the battery drain went back to almost normal. I noticed some increase in battery consumption on my phone, but I can't say for sure if it has to do with the integration. However, since I already have HA Companion as a tracker, I think I'm going to disable the phone as well. But the integration is perfect for tags, which are not online.

**Comment by Vedeneb** [comment]
Thanks for your comments and sorry for my late reply. I'm quite busy currently.
I now can confirm that this integration indeed has a big impact on the battery life. I will pinn this issue and add a note to the Readme. I might as well disable phones/watches by default. However I actually also expect there to be a battery drain on SmartTags too, at least if they are close to the phone. This integration actively requests STF for new location updates which might (I'm not 100% sure on that) cause your phone to actively try to connect to the SmartTag which would also reduce it's battery life.

**Comment by Vedeneb** [comment]
Hi, just released v0.2.0 which addresses this issue by adding a "passive" mode which does not actively connect to the devices aymore.

**Comment by davidalben** [comment]
Hi. V0.2.0 worked fine at first sight, but stopped in some hours. Restarting integration or Home Assistant didn't came it back. My tags are "unavaliable". This is what I see in HA log:

```
Este erro originou-se de uma integração personalizada.

Registrador: custom_components.smartthings_find.utils
Fonte: custom_components/smartthings_find/utils.py:460
integração: SmartThings Find (documentação, problemas)
Ocorreu pela primeira vez: 19 de junho de 2024 às 16:00:25 (862 ocorrências)
Último registro: 09:42:26

[Watch4 de Davi] No operation found in response; marking update failed
[Galaxy Buds Live] No operation found in response; marking update failed
[Tab A9+ de Davi] No operation found in response; marking update failed
[S21 de Davi] No operation found in response; marking update failed
```

Any clue?

**Comment by Vedeneb** [comment]
Could you try to open the SmartThings Find website an check the devices location there? I guess after that they should be back in Home Assistant too.

This is of course not the solution, just to confirm I'm right with my assumption :)

**Comment by davidalben** [comment]
I had already tried to do this using my phone, without success. Now I tried using the website and waited 2 minutes for the integration to update, also without success. Tags still unavailable.

BUT, non-tag devices seem to be ok now.
