### ISSUE TITLE
Add an option to reconfigure without deleting and re-adding?

### ISSUE THREAD

**Issue by quack3d** [Vedeneb/HA-SmartThings-Find#16]
Periodically the component stops working where HA restart and "reload" doesn't help. The only thing that works is to delete the hub and add again with the QR code (maybe the token has timed out, I don't know). But then I have to disable the devices that should be disabled and change configurations. 

Is it possible to have an option in config that reloads the integration completely so we don't have to delete and add again?

**Comment by Vedeneb** [comment]
Yeah, I also experience stability issues recently. 
However, my exam period is starting now, which means I currently have even less time. From the end of July, I should have a bit more free time and hopefully will be able to take care of it by then.

**Comment by snigehere** [comment]
thanks for providing this really helpful integration.  I have had it installed since 25th June and it has just dropped my 4 trackers to unavailable - I deleted and re-install which allowed me to re-authorise and it solved it so my guess is the token was either timed out or dropped.  Other than that its been solid since install and useful while I was on holiday.

I will wait to see what you are able to do.

**Comment by mariosemes** [comment]
> Yeah, I also experience stability issues recently. However, my exam period is starting now, which means I currently have even less time. From the end of July, I should have a bit more free time and hopefully will be able to take care of it by then.

Amazing add-on and thanks for the hard work! Good luck with your exams!
This is a long awaited plugin for the whole community <3

**Comment by Vedeneb** [comment]
Hi, just published a small new release which allows to manually trigger the reauth flow by clicking on "reconfigure":

![image](https://github.com/user-attachments/assets/5bbb0a00-5ecd-4bc9-8da3-61db3805fd19)

Note that this is not the solution to the actual problem (devices becoming unavailable) but a workaround. The actual cause is tracked in #18.
